apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-test
  labels:
    app: ephemeral-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemeral-cache
  template:
    metadata:
      labels:
        app: ephemeral-cache
    spec:
      containers:
      - name: memcached
        image: memcached:1.6-alpine
        ports:
        - containerPort: 11211
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: memcached-service
spec:
  selector:
    app: ephemeral-cache
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211
  type: ClusterIP
